# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pipeline.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pipeline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epipeline.proto\x12\x0eimage_pipeline\"6\n\rUploadRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x11\n\tfile_name\x18\x02 \x01(\t\"7\n\x0eUploadResponse\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x11\n\tfile_name\x18\x02 \x01(\t\"+\n\x15NoiseReductionRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\",\n\x16NoiseReductionResponse\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"-\n\x17\x42\x61\x63kgroundRemoveRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\".\n\x18\x42\x61\x63kgroundRemoveResponse\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"%\n\x0f\x43lassifyRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"!\n\x10\x43lassifyResponse\x12\r\n\x05label\x18\x01 \x01(\t\"7\n\x0eProcessRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x11\n\tfile_name\x18\x02 \x01(\t\"\xc6\x01\n\x0fProcessResponse\x12\x1c\n\x14processed_image_data\x18\x01 \x01(\x0c\x12\x1c\n\x14\x63lassification_label\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x18\n\x10response_time_ms\x18\x05 \x01(\x02\x12\x1b\n\x13timeline_plot_image\x18\x06 \x01(\x0c\x12\x1e\n\x16timeline_plot_filename\x18\x07 \x01(\t2X\n\rImageUploader\x12G\n\x06Upload\x12\x1d.image_pipeline.UploadRequest\x1a\x1e.image_pipeline.UploadResponse2g\n\x0cNoiseReducer\x12W\n\x06Reduce\x12%.image_pipeline.NoiseReductionRequest\x1a&.image_pipeline.NoiseReductionResponse2p\n\x11\x42\x61\x63kgroundRemover\x12[\n\x06Remove\x12\'.image_pipeline.BackgroundRemoveRequest\x1a(.image_pipeline.BackgroundRemoveResponse2`\n\x0fImageClassifier\x12M\n\x08\x43lassify\x12\x1f.image_pipeline.ClassifyRequest\x1a .image_pipeline.ClassifyResponse2h\n\x1aImageProcessorOrchestrator\x12J\n\x07Process\x12\x1e.image_pipeline.ProcessRequest\x1a\x1f.image_pipeline.ProcessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pipeline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADREQUEST']._serialized_start=34
  _globals['_UPLOADREQUEST']._serialized_end=88
  _globals['_UPLOADRESPONSE']._serialized_start=90
  _globals['_UPLOADRESPONSE']._serialized_end=145
  _globals['_NOISEREDUCTIONREQUEST']._serialized_start=147
  _globals['_NOISEREDUCTIONREQUEST']._serialized_end=190
  _globals['_NOISEREDUCTIONRESPONSE']._serialized_start=192
  _globals['_NOISEREDUCTIONRESPONSE']._serialized_end=236
  _globals['_BACKGROUNDREMOVEREQUEST']._serialized_start=238
  _globals['_BACKGROUNDREMOVEREQUEST']._serialized_end=283
  _globals['_BACKGROUNDREMOVERESPONSE']._serialized_start=285
  _globals['_BACKGROUNDREMOVERESPONSE']._serialized_end=331
  _globals['_CLASSIFYREQUEST']._serialized_start=333
  _globals['_CLASSIFYREQUEST']._serialized_end=370
  _globals['_CLASSIFYRESPONSE']._serialized_start=372
  _globals['_CLASSIFYRESPONSE']._serialized_end=405
  _globals['_PROCESSREQUEST']._serialized_start=407
  _globals['_PROCESSREQUEST']._serialized_end=462
  _globals['_PROCESSRESPONSE']._serialized_start=465
  _globals['_PROCESSRESPONSE']._serialized_end=663
  _globals['_IMAGEUPLOADER']._serialized_start=665
  _globals['_IMAGEUPLOADER']._serialized_end=753
  _globals['_NOISEREDUCER']._serialized_start=755
  _globals['_NOISEREDUCER']._serialized_end=858
  _globals['_BACKGROUNDREMOVER']._serialized_start=860
  _globals['_BACKGROUNDREMOVER']._serialized_end=972
  _globals['_IMAGECLASSIFIER']._serialized_start=974
  _globals['_IMAGECLASSIFIER']._serialized_end=1070
  _globals['_IMAGEPROCESSORORCHESTRATOR']._serialized_start=1072
  _globals['_IMAGEPROCESSORORCHESTRATOR']._serialized_end=1176
# @@protoc_insertion_point(module_scope)
