# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pipeline_pb2 as pipeline__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pipeline_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageUploaderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upload = channel.unary_unary(
                '/image_pipeline.ImageUploader/Upload',
                request_serializer=pipeline__pb2.UploadRequest.SerializeToString,
                response_deserializer=pipeline__pb2.UploadResponse.FromString,
                _registered_method=True)


class ImageUploaderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Upload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageUploaderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Upload': grpc.unary_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=pipeline__pb2.UploadRequest.FromString,
                    response_serializer=pipeline__pb2.UploadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'image_pipeline.ImageUploader', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('image_pipeline.ImageUploader', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageUploader(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Upload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/image_pipeline.ImageUploader/Upload',
            pipeline__pb2.UploadRequest.SerializeToString,
            pipeline__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class NoiseReducerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Reduce = channel.unary_unary(
                '/image_pipeline.NoiseReducer/Reduce',
                request_serializer=pipeline__pb2.NoiseReductionRequest.SerializeToString,
                response_deserializer=pipeline__pb2.NoiseReductionResponse.FromString,
                _registered_method=True)


class NoiseReducerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Reduce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NoiseReducerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Reduce': grpc.unary_unary_rpc_method_handler(
                    servicer.Reduce,
                    request_deserializer=pipeline__pb2.NoiseReductionRequest.FromString,
                    response_serializer=pipeline__pb2.NoiseReductionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'image_pipeline.NoiseReducer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('image_pipeline.NoiseReducer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NoiseReducer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Reduce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/image_pipeline.NoiseReducer/Reduce',
            pipeline__pb2.NoiseReductionRequest.SerializeToString,
            pipeline__pb2.NoiseReductionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BackgroundRemoverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Remove = channel.unary_unary(
                '/image_pipeline.BackgroundRemover/Remove',
                request_serializer=pipeline__pb2.BackgroundRemoveRequest.SerializeToString,
                response_deserializer=pipeline__pb2.BackgroundRemoveResponse.FromString,
                _registered_method=True)


class BackgroundRemoverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BackgroundRemoverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=pipeline__pb2.BackgroundRemoveRequest.FromString,
                    response_serializer=pipeline__pb2.BackgroundRemoveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'image_pipeline.BackgroundRemover', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('image_pipeline.BackgroundRemover', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BackgroundRemover(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/image_pipeline.BackgroundRemover/Remove',
            pipeline__pb2.BackgroundRemoveRequest.SerializeToString,
            pipeline__pb2.BackgroundRemoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ImageClassifierStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Classify = channel.unary_unary(
                '/image_pipeline.ImageClassifier/Classify',
                request_serializer=pipeline__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=pipeline__pb2.ClassifyResponse.FromString,
                _registered_method=True)


class ImageClassifierServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Classify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageClassifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Classify': grpc.unary_unary_rpc_method_handler(
                    servicer.Classify,
                    request_deserializer=pipeline__pb2.ClassifyRequest.FromString,
                    response_serializer=pipeline__pb2.ClassifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'image_pipeline.ImageClassifier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('image_pipeline.ImageClassifier', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageClassifier(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Classify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/image_pipeline.ImageClassifier/Classify',
            pipeline__pb2.ClassifyRequest.SerializeToString,
            pipeline__pb2.ClassifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ImageProcessorOrchestratorStub(object):
    """Orchestrator service that calls the above microservices
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Process = channel.unary_unary(
                '/image_pipeline.ImageProcessorOrchestrator/Process',
                request_serializer=pipeline__pb2.ProcessRequest.SerializeToString,
                response_deserializer=pipeline__pb2.ProcessResponse.FromString,
                _registered_method=True)


class ImageProcessorOrchestratorServicer(object):
    """Orchestrator service that calls the above microservices
    """

    def Process(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageProcessorOrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Process': grpc.unary_unary_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=pipeline__pb2.ProcessRequest.FromString,
                    response_serializer=pipeline__pb2.ProcessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'image_pipeline.ImageProcessorOrchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('image_pipeline.ImageProcessorOrchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageProcessorOrchestrator(object):
    """Orchestrator service that calls the above microservices
    """

    @staticmethod
    def Process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/image_pipeline.ImageProcessorOrchestrator/Process',
            pipeline__pb2.ProcessRequest.SerializeToString,
            pipeline__pb2.ProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
